---
kind: pipeline
type: docker
name: build and test
platform:
  os: linux
  arch: arm
trigger:
  event:
    exclude:
    - tag
    include:
    - push

steps:
- name: check format
  failure: ignore
  image: docker.claudiomattera.it/claudiomattera/rust:1.48.0
  commands:
  - cargo fmt --all -- --check

- name: run linter
  failure: ignore
  image: docker.claudiomattera.it/claudiomattera/rust:1.48.0
  commands:
  - cargo clippy --all-targets --all-features -- -D warnings

- name: build
  image: docker.claudiomattera.it/claudiomattera/rust:1.48.0
  commands:
  - cargo build --all-targets --all-features

- name: test
  image: docker.claudiomattera.it/claudiomattera/rust:1.48.0
  commands:
  - cargo test

---
kind: pipeline
type: docker
name: build release
platform:
  os: linux
  arch: arm
trigger:
  event:
  - tag

steps:
- name: build
  image: docker.claudiomattera.it/claudiomattera/rust:1.48.0
  commands:
  - cargo build --release

- name: package deb
  image: rust:latest
  commands:
  - cargo deb --no-build

- name: create release on gitea
  image: plugins/gitea-release
  settings:
    base_url:
      from_secret: gitea_host
    api_key:
      from_secret: gitea_token
    files:
      - target/release/${DRONE_REPO_NAME}
      - target/debian/${DRONE_REPO_NAME}_${DRONE_TAG}_armhf.deb
    checksum:
      - sha512

---
kind: pipeline
type: docker
name: notification

depends_on:
- build and test

trigger:
  event:
    exclude:
    - tag
  status:
  - failure

platform:
  os: linux
  arch: arm

steps:
- name: notification
  image: docker.claudiomattera.it/claudiomattera/drone-gotify:1
  settings:
    host:
      from_secret: gotify_host
    token:
      from_secret: gotify_token
    title: >
        ✗ Build {{drone.build.number}} failed for {{drone.repo.name}}
    message: >
        Commit *{{drone.commit.message | trim}}* pushed by {{drone.commit.author}} on {{drone.commit.branch}}

        Failed stages:

        {% for stage in drone.failed.stages | split(pat=",") %}
        - {{ stage }}
        {% endfor %}

        {% set build_link = drone.system.proto ~ "://" ~ drone.system.host ~ "/" ~ drone.repo.owner ~ "/" ~ drone.repo.name ~ "/" ~ drone.build.number -%}
        See the complete report at <{{ build_link }}>.

---
kind: pipeline
type: docker
name: notification release

depends_on:
- build release

trigger:
  event:
  - tag
  status:
  - success
  - failure

platform:
  os: linux
  arch: arm

steps:
- name: notification
  image: docker.claudiomattera.it/claudiomattera/drone-gotify:1
  settings:
    host:
      from_secret: gotify_host
    token:
      from_secret: gotify_token
    title: >
        {% if drone.build.status == "success" %}
        ✓ Release build succeeded for {{drone.repo.name}}-{{drone.tag}}
        {% else %}
        ✗ Release build failed for {{drone.repo.name}}-{{drone.tag}}
        {% endif %}
    message: >
        {% if drone.build.status == "success" %}
        {% else %}
        Failed steps:

          {% for stage in drone.failed.stages | split(pat=",") %}
          - {{ stage }}
          {% endfor %}
        {% endif %}

        {% set build_link = drone.system.proto ~ "://" ~ drone.system.host ~ "/" ~ drone.repo.owner ~ "/" ~ drone.repo.name ~ "/" ~ drone.build.number -%}
        See the complete report at <{{ build_link }}>.
