[workspace]
members = [
    "house-dashboard",
    "house-dashboard-common",
    "house-dashboard-influxdb",
    "house-dashboard-infrastructure-summary",
    "house-dashboard-proxmox-summary",
    "house-dashboard-trend",
    "house-dashboard-geographical-heatmap",
    "house-dashboard-temporal-heatmap",
    "house-dashboard-image",
]

[workspace.package]
version = "1.0.0"
authors = ["Claudio Mattera <dev@claudiomattera.it>"]
edition = "2021"
description = "An application to generate and display charts for a house dashboard"
readme = "Readme.md"
homepage = "https://gitlab.com/claudiomattera/house-dashboard"
repository = "https://gitlab.com/claudiomattera/house-dashboard"
license = "MPL-2.0"
keywords = [
    "dashboard",
]
categories = [
    "command-line-utilities",
]
publish = false

[profile.release]
# Necessary for release builds on Raspberry Pi
# https://github.com/rust-lang/cargo/issues/6489
# https://github.com/rust-lang/rust/issues/62896
codegen-units = 1

lto = "thin"
strip = "debuginfo"
