[workspace]
members = [
    "house-dashboard",
    "house-dashboard-common",
    "house-dashboard-infrastructure-summary",
    "house-dashboard-trend",
]

[profile.release]
# Necessary for release builds on Raspberry Pi
# https://github.com/rust-lang/cargo/issues/6489
# https://github.com/rust-lang/rust/issues/62896
codegen-units=1
