[package]
name = "house-dashboard"
version = "0.14.0"
authors = ["Claudio Mattera <claudio@mattera.it>"]
edition = "2018"
description = "An application to generate and display charts for a house dashboard"
readme = "Readme.md"
homepage = "https://gitlab.com/claudiomattera/house-dashboard"
repository = "https://gitlab.com/claudiomattera/house-dashboard"
license = "MIT"
keywords = [
    "dashboard",
]
categories = [
    "command-line-utilities",
]
publish = false

[features]
default = []
trend-chart = []
temporal-heatmap-chart = []
geographical-heatmap-chart = []
image-chart = []
infrastructure-chart = []
proxmox-chart = []

[dependencies]
thiserror = { version = "1.0" }
anyhow = { version = "1.0" }
clap = { version = "2.33" }
chrono = { version = "0.4" }
serde_json = { version = "1.0" }
num-traits = { version = "0.2" }
framebuffer = { version = "0.3", optional = true }
toml = { version = "0.5" }
glob = { version = "0.3" }
regex = { version = "1" }
indicatif = { version = "0.16" }
tracing = { version = "0.1" }
tracing-futures = { version = "0.2" }
tracing-subscriber = { version = "0.2", features = ["registry", "env-filter"] }
tracing-log = { version = "0.1" }
url = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
palette = { version = "^0.5", default-features = false, features = ["std"] }
image = { version = "0.23", default-features = false, features = ["jpeg", "png", "bmp"] }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros"] }
futures = { version = "0.3" }

[dependencies.plotters]
version = "0.2"
# default-features = false
# features = ["image_encoder", "line_series", "datetime"]

[package.metadata.deb]
extended-description = """\
This application generates charts for a house dashboard.
Charts are dynamically configured through a TOML file, and their data is
fetched from an InfluxDB instance."""
section = "utility"

[profile.release]
# Necessary for release builds on Raspberry Pi
# https://github.com/rust-lang/cargo/issues/6489
# https://github.com/rust-lang/rust/issues/62896
codegen-units=1
