[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.fetch]
script = '''
cargo fetch --locked
'''

[tasks.check-format]
dependencies = ["fetch"]
script = '''
cargo fmt --all -- --check
'''

[tasks.format]
dependencies = ["fetch"]
script = '''
cargo fmt --all --
'''

[tasks.lint]
dependencies = ["fetch"]
script = '''
cargo clippy --frozen --all-targets --all-features -- -D warnings
'''

[tasks.check]
dependencies = ["fetch"]
script = '''
cargo check --frozen --all-features
'''

[tasks.build]
dependencies = ["fetch"]
script = '''
cargo build --frozen --all-targets --all-features
'''

[tasks.build-tests]
dependencies = ["fetch"]
script = '''
cargo test --frozen --all-features --no-run
'''

[tasks.test]
dependencies = ["build-tests"]
script = '''
cargo test --frozen --all-features
'''

[tasks.prepare-cache]
script = '''
find ./target/debug -maxdepth 1 -type f -and -not -name xtask.exe -delete
rm -rf ./target/.rustc_info.json
'''

[tasks.build-release]
script = '''
cargo build --frozen --all-features --release
strip target/release/house-dashboard
'''

[tasks.clean-release]
script = '''
cargo clean --release --frozen
'''

[tasks.clean]
script = '''
cargo clean --frozen
'''

[tasks.deb]
script = '''
cargo deb --no-build
'''

[tasks.audit]
script = '''
cargo audit --deny unsound --deny yanked
'''
