[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.fetch]
script = '''
cargo fetch --locked
'''

[tasks.check-format]
dependencies = ["fetch"]
script = '''
cargo fmt --all -- --check
'''

[tasks.format]
dependencies = ["fetch"]
script = '''
cargo fmt --all --
'''

[tasks.lint]
dependencies = ["fetch"]
script = '''
cargo clippy --frozen --all-targets --all-features -- -D warnings
'''

[tasks.check]
dependencies = ["fetch"]
script = '''
cargo check --frozen --all-targets --all-features
'''

[tasks.build]
dependencies = ["fetch"]
script = '''
cargo build --frozen --all-features
'''

[tasks.run]
dependencies = ["build"]
script = '''
cargo run --frozen --all-features -- $@
'''

[tasks.build-tests]
dependencies = ["fetch"]
script = '''
cargo test --frozen --all-features --no-run
'''

[tasks.test]
dependencies = ["build-tests"]
script = '''
env RUST_LOG=trace cargo test --frozen --all-features $@
'''

[tasks.mutants]
dependencies = ["fetch"]
description = "Run mutation testing tool"
script = '''
cargo mutants --caught --dir house-dashboard -- --target=x86_64-unknown-linux-gnu --package house-dashboard
'''

[tasks.build-release]
dependencies = ["fetch"]
script = '''
env RUSTC_WRAPPER="" cargo auditable build --frozen --all-features --release
'''

[tasks.clean-release]
script = '''
cargo clean --release --frozen
'''

[tasks.clean]
script = '''
cargo clean --frozen
'''

[tasks.audit]
script = '''
cargo audit --deny unsound --deny yanked
'''

[tasks.audit-binary]
script = '''
cargo audit bin --deny unsound --deny yanked $@
'''
